# Generated by Django 6.0.5 on 2026-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_moderated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="moderation_notes",
            field=models.TextField(blank=True),
        ),
    ]
