# Generated by Django 6.0.5 on 2026-05-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order placed"),
                            ("PAYMENT_CONFIRMED", "Payment confirmed"),
                            ("VENDOR_NOTIFIED", "Vendor notified"),
                            ("ORDER_ACCEPTED", "Order accepted"),
                            ("IN_PREPARATION", "In preparation"),
                            ("DISPATCHED", "Dispatched"),
                            ("IN_TRANSIT", "In transit"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("DISPUTED", "Disputed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "checkpoints",
                "ordering": ["timestamp"],
            },
        ),
    ]
