# Generated by Django 6.0.5 on 2026-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="photo_proof",
            field=models.ImageField(blank=True, upload_to="checkpoints/proofs/"),
        ),
    ]
