# Generated by Django 6.0.5 on 2026-05-30 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_moderated_product_moderation_notes"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorKYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_legal_name", models.CharField(max_length=255)),
                ("ghana_card_number", models.CharField(max_length=20, unique=True)),
                ("ghana_card_front", models.ImageField(upload_to="kyc/ghana_card/")),
                ("ghana_card_back", models.ImageField(upload_to="kyc/ghana_card/")),
                ("selfie_with_card", models.ImageField(upload_to="kyc/selfies/")),
                ("phone_number", models.CharField(max_length=20)),
                ("business_address", models.TextField()),
                ("business_reg_number", models.CharField(blank=True, max_length=100)),
                (
                    "business_reg_cert",
                    models.ImageField(blank=True, upload_to="kyc/business_certs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("reviewing", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_kyc",
            },
        ),
    ]
