# Generated by Django 6.0.5 on 2026-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "featured_listing_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Platform Setting",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]
